//! Token model — the semantic color vocabulary every renderer speaks.
//!
//! Ported from omp `theme/schema.ts`: one flat set of foreground tokens
//! (`ThemeColor`) plus the fixed set of background tokens (`ThemeBg`).
//! Theme JSON maps each token to a concrete color; renderers only ever
//! name the token, never a value. Adding a token means adding it here and
//! to every bundled theme — the loader rejects a theme missing any of them.
//!
//! omp's `bashMode` / `pythonMode` / mermaid / latex tokens are dropped
//! (no such features here); everything chat-visible is kept.

use serde::{Deserialize, Serialize};

/// Foreground color tokens. The string values are the JSON keys.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ColorToken {
    Accent,
    Border,
    BorderAccent,
    BorderMuted,
    Success,
    Error,
    Warning,
    Muted,
    Dim,
    Text,
    ThinkingText,
    UserMessageBg,
    UserMessageText,
    ToolPendingBg,
    ToolSuccessBg,
    ToolErrorBg,
    ToolTitle,
    ToolOutput,
    MdHeading,
    MdLink,
    MdLinkUrl,
    MdCode,
    MdCodeBlock,
    MdCodeBlockBorder,
    MdQuote,
    MdQuoteBorder,
    MdHr,
    MdListBullet,
    ToolDiffAdded,
    ToolDiffRemoved,
    ToolDiffContext,
    SyntaxComment,
    SyntaxKeyword,
    SyntaxFunction,
    SyntaxVariable,
    SyntaxString,
    SyntaxNumber,
    SyntaxType,
    SyntaxOperator,
    SyntaxPunctuation,
    ThinkingOff,
    ThinkingMinimal,
    ThinkingLow,
    ThinkingMedium,
    ThinkingHigh,
    ThinkingXhigh,
    StatusLineBg,
    StatusLineSep,
    StatusLineModel,
    StatusLinePath,
    StatusLineGitClean,
    StatusLineGitDirty,
    StatusLineContext,
    StatusLineSpend,
    StatusLineStaged,
    StatusLineDirty,
    StatusLineUntracked,
    StatusLineOutput,
    StatusLineCost,
    StatusLineSubagents,
}

/// Every color token, in declaration order (JSON completeness check).
pub const ALL_TOKENS: &[ColorToken] = &[
    ColorToken::Accent,
    ColorToken::Border,
    ColorToken::BorderAccent,
    ColorToken::BorderMuted,
    ColorToken::Success,
    ColorToken::Error,
    ColorToken::Warning,
    ColorToken::Muted,
    ColorToken::Dim,
    ColorToken::Text,
    ColorToken::ThinkingText,
    ColorToken::UserMessageBg,
    ColorToken::UserMessageText,
    ColorToken::ToolPendingBg,
    ColorToken::ToolSuccessBg,
    ColorToken::ToolErrorBg,
    ColorToken::ToolTitle,
    ColorToken::ToolOutput,
    ColorToken::MdHeading,
    ColorToken::MdLink,
    ColorToken::MdLinkUrl,
    ColorToken::MdCode,
    ColorToken::MdCodeBlock,
    ColorToken::MdCodeBlockBorder,
    ColorToken::MdQuote,
    ColorToken::MdQuoteBorder,
    ColorToken::MdHr,
    ColorToken::MdListBullet,
    ColorToken::ToolDiffAdded,
    ColorToken::ToolDiffRemoved,
    ColorToken::ToolDiffContext,
    ColorToken::SyntaxComment,
    ColorToken::SyntaxKeyword,
    ColorToken::SyntaxFunction,
    ColorToken::SyntaxVariable,
    ColorToken::SyntaxString,
    ColorToken::SyntaxNumber,
    ColorToken::SyntaxType,
    ColorToken::SyntaxOperator,
    ColorToken::SyntaxPunctuation,
    ColorToken::ThinkingOff,
    ColorToken::ThinkingMinimal,
    ColorToken::ThinkingLow,
    ColorToken::ThinkingMedium,
    ColorToken::ThinkingHigh,
    ColorToken::ThinkingXhigh,
    ColorToken::StatusLineBg,
    ColorToken::StatusLineSep,
    ColorToken::StatusLineModel,
    ColorToken::StatusLinePath,
    ColorToken::StatusLineGitClean,
    ColorToken::StatusLineGitDirty,
    ColorToken::StatusLineContext,
    ColorToken::StatusLineSpend,
    ColorToken::StatusLineStaged,
    ColorToken::StatusLineDirty,
    ColorToken::StatusLineUntracked,
    ColorToken::StatusLineOutput,
    ColorToken::StatusLineCost,
    ColorToken::StatusLineSubagents,
];

impl ColorToken {
    /// The camelCase JSON key this token reads from a theme file.
    pub fn json_key(self) -> &'static str {
        match self {
            ColorToken::Accent => "accent",
            ColorToken::Border => "border",
            ColorToken::BorderAccent => "borderAccent",
            ColorToken::BorderMuted => "borderMuted",
            ColorToken::Success => "success",
            ColorToken::Error => "error",
            ColorToken::Warning => "warning",
            ColorToken::Muted => "muted",
            ColorToken::Dim => "dim",
            ColorToken::Text => "text",
            ColorToken::ThinkingText => "thinkingText",
            ColorToken::UserMessageBg => "userMessageBg",
            ColorToken::UserMessageText => "userMessageText",
            ColorToken::ToolPendingBg => "toolPendingBg",
            ColorToken::ToolSuccessBg => "toolSuccessBg",
            ColorToken::ToolErrorBg => "toolErrorBg",
            ColorToken::ToolTitle => "toolTitle",
            ColorToken::ToolOutput => "toolOutput",
            ColorToken::MdHeading => "mdHeading",
            ColorToken::MdLink => "mdLink",
            ColorToken::MdLinkUrl => "mdLinkUrl",
            ColorToken::MdCode => "mdCode",
            ColorToken::MdCodeBlock => "mdCodeBlock",
            ColorToken::MdCodeBlockBorder => "mdCodeBlockBorder",
            ColorToken::MdQuote => "mdQuote",
            ColorToken::MdQuoteBorder => "mdQuoteBorder",
            ColorToken::MdHr => "mdHr",
            ColorToken::MdListBullet => "mdListBullet",
            ColorToken::ToolDiffAdded => "toolDiffAdded",
            ColorToken::ToolDiffRemoved => "toolDiffRemoved",
            ColorToken::ToolDiffContext => "toolDiffContext",
            ColorToken::SyntaxComment => "syntaxComment",
            ColorToken::SyntaxKeyword => "syntaxKeyword",
            ColorToken::SyntaxFunction => "syntaxFunction",
            ColorToken::SyntaxVariable => "syntaxVariable",
            ColorToken::SyntaxString => "syntaxString",
            ColorToken::SyntaxNumber => "syntaxNumber",
            ColorToken::SyntaxType => "syntaxType",
            ColorToken::SyntaxOperator => "syntaxOperator",
            ColorToken::SyntaxPunctuation => "syntaxPunctuation",
            ColorToken::ThinkingOff => "thinkingOff",
            ColorToken::ThinkingMinimal => "thinkingMinimal",
            ColorToken::ThinkingLow => "thinkingLow",
            ColorToken::ThinkingMedium => "thinkingMedium",
            ColorToken::ThinkingHigh => "thinkingHigh",
            ColorToken::ThinkingXhigh => "thinkingXhigh",
            ColorToken::StatusLineBg => "statusLineBg",
            ColorToken::StatusLineSep => "statusLineSep",
            ColorToken::StatusLineModel => "statusLineModel",
            ColorToken::StatusLinePath => "statusLinePath",
            ColorToken::StatusLineGitClean => "statusLineGitClean",
            ColorToken::StatusLineGitDirty => "statusLineGitDirty",
            ColorToken::StatusLineContext => "statusLineContext",
            ColorToken::StatusLineSpend => "statusLineSpend",
            ColorToken::StatusLineStaged => "statusLineStaged",
            ColorToken::StatusLineDirty => "statusLineDirty",
            ColorToken::StatusLineUntracked => "statusLineUntracked",
            ColorToken::StatusLineOutput => "statusLineOutput",
            ColorToken::StatusLineCost => "statusLineCost",
            ColorToken::StatusLineSubagents => "statusLineSubagents",
        }
    }

    /// Background tokens get `bg()` styling; everything else is foreground.
    pub fn is_background(self) -> bool {
        matches!(
            self,
            ColorToken::UserMessageBg
                | ColorToken::ToolPendingBg
                | ColorToken::ToolSuccessBg
                | ColorToken::ToolErrorBg
                | ColorToken::StatusLineBg
        )
    }
}
