//! Message contracts — mirrors pi's packages/ai/src/types.ts.
//!
//! pi spends 1000 lines on a superset covering every vendor; we only need
//! the minimal OpenAI-compatible subset. Each struct maps directly onto
//! the JSON fields of the wire format; serde does the JSON <-> struct
//! conversion automatically.
//!
//! # The four roles
//!
//! `system` / `user` / `assistant` / `tool` — the full set the OpenAI
//! spec allows, no way around it. A tool call is completed by **two
//! messages**:
//!
//! ```text
//! 1. assistant says "call read_file"         -> Message::Assistant { tool_calls }
//! 2. we execute and send back a tool message -> Message::Tool { tool_call_id }
//! ```
//!
//! The `tool_call_id` on the second is the pairing key; never guess by
//! order (a model may place several parallel calls per turn and the
//! return order is not guaranteed).

use serde::{Deserialize, Serialize};
use serde_json::Value;

// One conversation message. The role is its identity within the messages array.
//
// Why a tagged enum instead of four separate structs: the messages
// array mixes roles and is discriminated by the "role" field on the
// wire — exactly serde's internally-tagged representation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "role", rename_all = "snake_case")]
pub enum Message {
    // System prompt. By convention the first array entry; plain text at heart.
    System {
        content: String,
    },
    // User input.
    User {
        content: String,
    },
    // The model reply.
    //
    // Either field may be empty depending on what the model did this
    // round:
    //
    // | round        | content    | tool_calls |
    // | --- | --- | --- |
    // | text only    | `Some(..)` | empty      |
    // | tools only   | `None`     | non-empty  |
    // | text + tools | `Some(..)` | non-empty  |
    Assistant {
        // Content. `None` in pure tool-call rounds.
        //
        // This must serialize as an explicit `null`, not an omitted
        // field: the OpenAI convention for tool-call rounds is
        // `"content": null`. `skip_serializing_if` was tried once — the
        // field vanished, strict gateways rejected the request as
        // malformed, and the error never said why.
        #[serde(default, serialize_with = "serialize_content")]
        content: Option<String>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        tool_calls: Vec<ToolCall>,
    },
    // Tool execution result. `tool_call_id` pairs it with the call that
    // started it.
    //
    // Modern OpenAI-compatible layers only need `tool_call_id`; older
    // gateways also want `name` (pi's `requiresToolResultName` exists
    // for that). Omitted until a real gateway demands it — a permanently
    // redundant field is worse than none.
    Tool {
        tool_call_id: String,
        content: String,
    },
}

impl Message {
    /// Rough character count of the message content — feeds the cheap
    /// context estimate used to shrink the requested `max_tokens`. NOT a
    /// tokenizer: billing and the ctx gauge always use the real usage
    /// the gateway reports back.
    pub fn approx_chars(&self) -> usize {
        match self {
            Message::User { content } => content.len(),
            Message::Assistant { content, tool_calls } => {
                content.as_deref().unwrap_or("").len()
                    + tool_calls.iter().map(|c| c.function.arguments.len() + c.function.name.len()).sum::<usize>()
            }
            Message::Tool { content, .. } => content.len(),
            Message::System { content } => content.len(),
        }
    }
}

// Content serialization for `Option<String>`: `None` becomes JSON
// `null` rather than an omitted field (which serde default behavior
// would choose depends on attributes; we need the explicit null).
fn serialize_content<S: serde::Serializer>(v: &Option<String>, s: S) -> Result<S::Ok, S::Error> {
    match v {
        Some(t) => s.serialize_some(t),
        None => s.serialize_none(),
    }
}

// A tool call requested by the model.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolCall {
    // Unique id of this call, generated by the model (e.g. `call_abc123`).
    pub id: String,
    // Always `"function"`. Kept so the wire shape matches exactly —
    // the field is required in JSON and strict gateways reject its
    // absence.
    #[serde(rename = "type", default = "function_kind")]
    pub kind: String,
    pub function: FunctionCall,
}

// Tool name plus arguments.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct FunctionCall {
    pub name: String,
    // **Raw JSON text**, not a parsed object.
    //
    // Three reasons, the last one matters most:
    //
    // 1. On the wire it is a string (`"arguments":"{\"path\":\"a\"}"`);
    //    storing a `Value` would mean converting back and forth.
    // 2. Malformed arguments (models occasionally emit invalid JSON) do
    //    not explode in the parsing layer; the executor reports a
    //    readable error instead.
    // 3. **Prefix caching requires byte-identical history**: the next
    //    turn re-sends this assistant message verbatim. A round-trip
    //    through `Value` may reorder keys or change whitespace, making
    //    the request prefix differ from the previous turn and missing
    //    the cache. Raw text never has that problem.
    //
    // Use [`FunctionCall::arguments_json`] to parse.
    pub arguments: String,
}

// Tool definition — the "manual" we send to the model.
//
// Request direction only (the model never sends this back), hence `Serialize` alone.
#[derive(Debug, Clone, Serialize)]
pub struct ToolDef {
    #[serde(rename = "type")]
    pub kind: &'static str,
    pub function: FunctionDef,
}

// The manual body. `parameters` is a JSON Schema.
#[derive(Debug, Clone, Serialize)]
pub struct FunctionDef {
    pub name: String,
    pub description: String,
    pub parameters: Value,
}

impl FunctionCall {
    // Parse arguments. Failures carry readable context, not a bare serde error.
    pub fn arguments_json(&self) -> serde_json::Result<Value> {
        serde_json::from_str(&self.arguments)
    }
}

fn function_kind() -> String {
    "function".to_string()
}

impl ToolCall {
    // Build a call (`kind` filled here; callers never touch the constant).
    pub fn new(id: impl Into<String>, name: impl Into<String>, arguments: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            kind: function_kind(),
            function: FunctionCall {
                name: name.into(),
                arguments: arguments.into(),
            },
        }
    }

    // Tool name (saves one `.function.` hop).
    pub fn name(&self) -> &str {
        &self.function.name
    }
    // Parse arguments. Failures carry readable context, not a bare serde error.
    pub fn arguments_json(&self) -> serde_json::Result<Value> {
        self.function.arguments_json()
    }
}

impl ToolDef {
    pub fn function(
        name: impl Into<String>,
        description: impl Into<String>,
        parameters: Value,
    ) -> Self {
        Self {
            kind: "function",
            function: FunctionDef {
                name: name.into(),
                description: description.into(),
                parameters,
            },
        }
    }
}

// A conversation context: everything sent to the model.
//
// Corresponds to pi's TranscriptContext. Keep the core mental model in
// mind: the API is stateless, this struct is the model's entire memory,
// re-sent in full every turn.
//
// Tool definitions live here rather than inside `Client`: they are part
// of the outgoing content,
// Travel with the request, so `stream(ctx, ..)` needs no signature change to add tools.
#[derive(Debug, Clone, Default)]
pub struct Context {
    pub messages: Vec<Message>,
    pub tools: Vec<ToolDef>,
}

impl Context {
    pub fn new() -> Self {
        Self::default()
    }

    // Append a message (builder style, chainable).
    pub fn push(mut self, msg: Message) -> Self {
        self.messages.push(msg);
        self
    }

    // Append a tool definition.
    pub fn tool(mut self, def: ToolDef) -> Self {
        self.tools.push(def);
        self
    }
}

// Token usage stats.
//
// The three totals are required by the OpenAI spec (always present when
// usage appears); `_details` fields are optional extensions that
// gateways may or may not provide — hence all `Option`.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Usage {
    pub prompt_tokens: u64,
    pub completion_tokens: u64,
    pub total_tokens: u64,
    // Extension: reasoning tokens (thinking models only). Invisible but billed as output.
    #[serde(default)]
    pub reasoning_tokens: Option<u64>,
    // Extension: prefix cache hits. The lifeblood of agent-loop cost savings.
    #[serde(default)]
    pub cached_tokens: Option<u64>,
}

// Why the model stopped — maps to finish_reason; the loop's steering wheel.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    // Finished speaking.
    #[default]
    Stop,
    // Cut off by max_tokens, mid-sentence.
    Length,
    // The model is waiting for us to run tool calls.
    //
    // **The loop's only continue condition**: run the tools, append
    // results to history, request again; anything else means stop.
    ToolCalls,
    // User interrupt (Esc). The partial content received so far is usable.
    Interrupted,
}

// One complete model reply (given directly by non-streaming responses,
// assembled from deltas when streaming).
//
// Corresponds to pi's AssistantMessage — the "final shape" of its event
// stream; here it is the uniform type the loop layer consumes.
//
// Note `content` is an **assembled string** here but `Option<String>`
// in `Message::Assistant`. Not an inconsistency: this is "what we
// received", that is "what we send back", the latter bound by the
// wire's null convention.
#[derive(Debug, Clone, Default)]
pub struct AssistantMessage {
    pub content: String,
    // Tool calls placed this round. Empty means the model just talked.
    pub tool_calls: Vec<ToolCall>,
    pub stop_reason: StopReason,
    pub usage: Usage,
    // Reasoning content, when the model emits it (Qwen's
    // reasoning_content). Not replayed in later turns (kept out of
    // history; the server handles its own state).
    pub reasoning: Option<String>,
}

impl AssistantMessage {
    pub fn has_tool_calls(&self) -> bool {
        !self.tool_calls.is_empty()
    }

    // Convert to the `Message::Assistant` appended to history.
    //
    // Empty content serializes as `None`, not `Some("")`: pure
    // tool-call rounds want `null` per OpenAI. Most gateways accept an
    // empty string too, but there is no reason to gamble.
    pub fn to_message(&self) -> Message {
        Message::Assistant {
            content: if self.content.is_empty() {
                None
            } else {
                Some(self.content.clone())
            },
            tool_calls: self.tool_calls.clone(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // Pin the JSON shape of Message to the OpenAI wire format:
    // {"role": "user", "content": "..."} — tag flattened into the object.
    #[test]
    fn message_serializes_like_openai() {
        let msg = Message::User {
            content: "hi".into(),
        };
        let json = serde_json::to_value(&msg).unwrap();
        assert_eq!(json, serde_json::json!({"role": "user", "content": "hi"}));

        let back: Message = serde_json::from_value(json).unwrap();
        assert_eq!(back, msg);
    }

    #[test]
    fn usage_deserializes_without_details() {
        // Gateways may omit _details; must not explode
        let usage: Usage =
            serde_json::from_str(r#"{"prompt_tokens":65,"completion_tokens":29,"total_tokens":94}"#)
                .unwrap();
        assert_eq!(usage.prompt_tokens, 65);
        assert_eq!(usage.reasoning_tokens, None);
    }

    // ---- Everything below was added for the tool-call layer ----

    #[test]
    fn assistant_with_tool_calls_serializes_the_way_openai_expects() {
        let msg = Message::Assistant {
            content: None,
            tool_calls: vec![ToolCall::new("call_1", "read_file", r#"{"path":"a.txt"}"#)],
        };
        let v = serde_json::to_value(&msg).unwrap();
        assert_eq!(
            v,
            json!({
                "role": "assistant",
                "content": null,
                "tool_calls": [{
                    "id": "call_1",
                    "type": "function",
                    "function": {"name": "read_file", "arguments": "{\"path\":\"a.txt\"}"}
                }]
            })
        );
    }

    #[test]
    fn assistant_without_tool_calls_omits_the_field_entirely() {
        // Plain replies must not grow an empty "tool_calls": [] — legal
        // JSON, but it changes the request prefix versus a no-tools
        // version and throws away the cache.
        let msg = Message::Assistant {
            content: Some("你好".into()),
            tool_calls: vec![],
        };
        let v = serde_json::to_value(&msg).unwrap();
        assert_eq!(v, json!({"role": "assistant", "content": "你好"}));
        assert!(v.get("tool_calls").is_none());
    }

    #[test]
    fn assistant_with_only_tool_calls_deserializes() {
        // Gateway replies may **omit the content field entirely** (not
        // null — absent). Without #[serde(default)] this fails with
        // missing field.
        let raw = r#"{"role":"assistant","tool_calls":[
            {"id":"c1","type":"function","function":{"name":"f","arguments":"{}"}}]}"#;
        let msg: Message = serde_json::from_str(raw).unwrap();
        match msg {
            Message::Assistant {
                content,
                tool_calls,
            } => {
                assert_eq!(content, None);
                assert_eq!(tool_calls.len(), 1);
                assert_eq!(tool_calls[0].name(), "f");
            }
            other => panic!("parsed into {other:?}"),
        }
    }

    #[test]
    fn tool_result_message_matches_wire_format() {
        let msg = Message::Tool {
            tool_call_id: "call_1".into(),
            content: "文件内容".into(),
        };
        let v = serde_json::to_value(&msg).unwrap();
        assert_eq!(
            v,
            json!({"role": "tool", "tool_call_id": "call_1", "content": "文件内容"})
        );
    }

    #[test]
    fn arguments_stay_byte_identical_through_a_round_trip() {
        // The cache's lifeblood: in verbatim, out verbatim.
        // Parsing into Value and re-serializing would reorder keys
        // (BTreeMap ordering), changing the request prefix across turns.
        let messy = r#"{ "z": 1,  "a": 2 }"#;
        let call = ToolCall::new("c", "f", messy);
        let msg = Message::Assistant {
            content: None,
            tool_calls: vec![call],
        };
        let v = serde_json::to_value(&msg).unwrap();
        assert_eq!(v["tool_calls"][0]["function"]["arguments"], messy);
    }

    #[test]
    fn arguments_json_parses_on_demand() {
        let call = ToolCall::new("c", "f", r#"{"path":"a.txt","n":3}"#);
        let v = call.arguments_json().unwrap();
        assert_eq!(v["path"], "a.txt");
        assert_eq!(v["n"], 3);

        // Bad arguments must not panic, only error — the executor handles it
        let bad = ToolCall::new("c", "f", "{不是 JSON");
        assert!(bad.arguments_json().is_err());
    }

    #[test]
    fn assistant_message_to_message_drops_empty_content() {
        let mut a = AssistantMessage {
            content: String::new(),
            tool_calls: vec![ToolCall::new("c", "f", "{}")],
            ..Default::default()
        };
        assert_eq!(
            a.to_message(),
            Message::Assistant {
                content: None,
                tool_calls: vec![ToolCall::new("c", "f", "{}")]
            }
        );

        a.content = "说了句话".into();
        assert_eq!(
            a.to_message(),
            Message::Assistant {
                content: Some("说了句话".into()),
                tool_calls: vec![ToolCall::new("c", "f", "{}")]
            }
        );
    }

    #[test]
    fn tool_def_serializes_nested_the_way_openai_expects() {
        let def = ToolDef::function(
            "read_file",
            "read a file",
            json!({"type": "object", "properties": {"path": {"type": "string"}}}),
        );
        let v = serde_json::to_value(&def).unwrap();
        assert_eq!(v["type"], "function");
        assert_eq!(v["function"]["name"], "read_file");
        assert_eq!(v["function"]["description"], "read a file");
        assert_eq!(v["function"]["parameters"]["type"], "object");
    }

    #[test]
    fn context_builder_collects_tools() {
        let ctx = Context::new()
            .push(Message::System {
                content: "sys".into(),
            })
            .tool(ToolDef::function("a", "d", json!({})))
            .tool(ToolDef::function("b", "d", json!({})));
        assert_eq!(ctx.messages.len(), 1);
        assert_eq!(ctx.tools.len(), 2);
    }
}
